---
# tasks file for ansible-role-cbsd

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ cbsd_log_dir }}"
    mode: 0755
    owner: "{{ cbsd_user }}"
    group: "{{ cbsd_group }}"
    state: directory
  notify: Restart cbsd

- name: Create db directory
  file:
    path: "{{ cbsd_db_dir }}"
    mode: 0755
    owner: "{{ cbsd_user }}"
    group: "{{ cbsd_group }}"
    state: directory
  notify: Restart cbsd

- name: Create cbsd.conf
  template:
    src: cbsd.conf.j2
    dest: "{{ cbsd_conf_file }}"
    validate: echo %s
  notify: Restart cbsd

- name: Start cbsd
  service:
    name: "{{ cbsd_service }}"
    enabled: true
    state: started
